version: '3'
services:
  frontend:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./app:/app
  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
      - "5002:5002"
    volumes:
      - ./app:/app
